export const MVP_REASONS: { [index: number]: string } = {
  1: "most eliminations",
  2: "planting the bomb",
  3: "defusing the bomb",
};

export const ROUND_END_REASONS: { [index: number]: string } = {
  1: "Target Successfully Bombed!",
  2: "The VIP has escaped.",
  3: "VIP has been assassinated",
  4: "The terrorists have escaped",
  5: "The CTs have prevented most of the terrorists from escaping!",
  6: "Escaping terrorists have all been neutralized",
  7: "The bomb has been defused!",
  8: "Counter-Terrorists Win!",
  9: "Terrorists Win! ",
  10: "Round Draw!",
  11: "All Hostages have been rescued",
  12: "Target has been saved! ",
  13: "Hostages have not been rescued!",
  14: "Terrorists have not escaped!",
  15: "VIP has not escaped! ",
  16: "Game Commencing! ",
  17: "Terrorists Surrender",
  18: "CTs Surrender",
};

export const FUNFACT_REASONS: { [index: string]: string } = {
  funfact_ace: "Ace!  %1$s killed the entire enemy team.",
  funfact_best_accuracy: "%1$s had an accuracy of %2$s%.",
  funfact_best_counterterrorist_accuracy: "%1$s had an accuracy of %2$s%, while their team's was %3$s%.",
  funfact_best_terrorist_accuracy: "%1$s had an accuracy of %2$s%, while their team's was %3$s%.",
  funfact_blind_kills: "%1$s killed %2$s enemies while flashbanged.",
  funfact_blind_kills_singular: "%1$s killed an enemy while flashbanged.",
  funfact_bomb_carriers: "%1$s killed %2$s separate bomb carriers in the last round.",
  funfact_bomb_planted_before_kill: "No players were killed prior to the bomb being planted.",
  funfact_bots_assumed: "%1$s assumed control of %2$s bots that round.",
  funfact_broke_windows: "%1$s shattered %2$s windows.",
  funfact_ct_accuracy: "Counter-Terrorists had the best accuracy with %2$s%.",
  funfact_ct_win_no_casualties: "Counter-Terrorists won without taking any casualties.",
  funfact_ct_win_no_kills: "Counter-Terrorists won without killing any Terrorists.",
  funfact_ct_win_time: "The CT team eliminated the T team in %2$s seconds.",
  funfact_damage_multiple_enemies: "%1$s did damage to %2$s enemies.",
  funfact_damage_no_kills: "%1$s had no kills, but did %2$s damage.",
  funfact_damage_with_grenade: "%1$s did %2$s total damage with grenades.",
  funfact_default_weapon: "%1$s won the round without picking up any weapons.",
  funfact_defended_bomb: "%1$s defended the planted bomb from %2$s enemies.",
  funfact_defuse_was_close_call_hundredths: "%1$s defused the bomb with 0.0%2$s seconds remaining.",
  funfact_defuse_was_close_call_tenths: "%1$s defused the bomb with 0.%2$s seconds remaining.",
  funfact_defuse_was_close_call_thousandths: "%1$s defused the bomb with 0.00%2$s seconds remaining.",
  funfact_defused_with_dropped_kit: "%1$s defused the bomb with a dropped defuse kit.",
  funfact_died_from_multiple_attackers: "%1$s took damage from %2$s enemies before dying.",
  funfact_domination: "%1$s dominated the most players.",
  funfact_donated_weapons: "%1$s donated %2$s weapons that round.",
  funfact_draw: "Match was restarted based on player votes.",
  funfact_empty_guns: "%1$s ran out of ammo using %2$s guns.",
  funfact_failed_bomb_plants: "%2$s Terrorists tried planting the bomb that round.",
  funfact_fall_damage: "%1$s took %2$s damage... from the earth.",
  funfact_fallback1: "The cake is a lie.",
  funfact_fallback2: "Yawn.",
  funfact_first_blood: "%1$s drew first blood %2$s seconds into the round.",
  funfact_first_kill: "%2$s seconds into the round, %1$s got the first kill.",
  funfact_grenades_thrown: "%1$s threw %2$s grenades that round.",
  funfact_items_dropped_value: "%1$s threw away $%2$s worth of supplies.",
  funfact_items_purchased: "%1$s bought %2$s items.",
  funfact_kill_defuser: "%1$s successfully stopped the bomb defuser.",
  funfact_kill_rescuer: "%1$s killed the hostage extractor.",
  funfact_kill_wounded_enemies: "%1$s finished off %2$s wounded enemies.",
  funfact_killed_before_dying: "%1$s killed %2$s players before dying.",
  funfact_killed_enemies: "%1$s killed %2$s opponents.",
  funfact_killed_half_of_enemies: "%1$s killed %2$s%% of the enemy team.",
  funfact_kills_grenades: "%1$s killed %2$s enemies with grenades.",
  funfact_kills_headshots: "%1$s killed %2$s enemies with headshots that round.",
  funfact_kills_with_last_round: "On %2$s occasions with only one bullet left, %1$s killed an enemy.",
  funfact_kills_with_last_round_singular: "%1$s killed an enemy with their last bullet.",
  funfact_kills_with_single_grenade: "%1$s hit %2$s enemies with one grenade.",
  funfact_kills_with_stattrak_weapon: "%1$s added %2$s kills to their StatTrak™ weapons that round.",
  funfact_knife_bomb_planter: "%1$s won on knife Level by killing the bomb planter.",
  funfact_knife_in_gunfight: "%1$s brought a knife to a gunfight.",
  funfact_knife_kills: "%1$s had %2$s knife kills this round.",
  funfact_knife_kills_singular: "%1$s killed an enemy with the knife.",
  funfact_knife_level_reached: "%1$s players reached gold knife level.",
  funfact_knife_without_ammo: "%1$s got %2$s knife kills after running out of ammo.",
  funfact_molotov_burns: "%1$s torched %2$s players with fire.",
  funfact_money_spent: "%1$s spent $%2$s that round.",
  funfact_nightvision_damage: "%1$s did %2$s damage while wearing nightvision.",
  funfact_num_times_jumped: "%1$s jumped %2$s times during the round.",
  funfact_number_of_overkills: "%1$s killed %2$s players they were already dominating.",
  funfact_pickup_bomb: "%1$s planted bomb after being owned by %2$s teammates.",
  funfact_posthumous_kills_with_grenade: "%1$s got %2$s grenade kills while dead.",
  funfact_posthumous_kills_with_grenade_singular: "%1$s killed an enemy with a grenade after dying.",
  funfact_pulled_trigger: "%1$s pulled the trigger %2$s times that match.",
  funfact_quarter_health: "%1$s killed %2$s players while under 25 health.",
  funfact_respawned: "%1$s respawned %2$s times during the match.",
  funfact_revenge: "%1$s got revenge on %2$s players.",
  funfact_revenge_singular: "%1$s got revenge on %2$s player.",
  funfact_rounds_without_dying: "%1$s lasted %2$s consecutive rounds without dying.",
  funfact_short_round: "That round took only %2$s seconds!",
  funfact_shots_fired: "%2$s shots were fired that round.",
  funfact_slow_trigger: "%1$s died without firing a shot using %2$s guns.",
  funfact_steps_taken: "%1$s ran %2$s steps during the match.",
  funfact_survival_time: "%1$s survived the longest: %2$s seconds.",
  funfact_survived_multiple_attackers: "%1$s survived attacks from %2$s different enemies.",
  funfact_t_win_no_casualties: "Terrorists won without taking any casualties.",
  funfact_t_win_no_kills: "Terrorists won without killing any Counter-Terrorists.",
  funfact_taser_kill: "%1$s tased %2$s players.",
  funfact_taser_kill_singular: "%1$s tased %2$s player.",
  funfact_ter_win_time: "The Terrorist team eliminated the CT team in %2$s seconds.",
  funfact_terrorist_accuracy: "Terrorists had the best accuracy with %2$s%.",
  funfact_ticking_time: "Terrorists won despite %2$s CTs trying to defuse the bomb.",
  funfact_used_all_ammo: "%1$s went completely dry on ammo.",
  funfact_used_multiple_weapons: "%1$s used %2$s different firearms.",
  funfact_won_as_last_member: "As the last member alive, %1$s killed %2$s enemies and won.",
};

export const GRENADE_TYPES = [
  "weapon_flashbang",
  "weapon_hegrenade",
  "weapon_incgrenade",
  "weapon_molotov",
  "weapon_smokegrenade",
];


// export const ROUND_END_REASONS: { [index: number]: string } = {
export const HITGROUPS:{ [index: number]: string } = {
  0: "Generic",
  1: "Head",
  2: "Chest",
  3: "Stomach",
  4: "LeftArm",
  5: "RightArm",
  6: "LeftLeg",
  7: "RightLeg",
  10: "Gear",
};
